source 'https://rubygems.org'

gem 'sinatra', '~> 1.4.5'
gem 'activerecord', '~> 4.2.1'
gem 'sinatra-activerecord', '~> 2.0.6'
gem 'sqlite3', '~> 1.3.10'
gem 'rake', '~> 10.3.2'

group :development do
  gem 'thin', '~> 1.7.2'
  gem 'faker', '~> 1.6.3'
end

group :test do
  gem 'rspec', '~> 3.1.0'
  gem 'rack-test', '~> 0.6.2'
end
